
title: "MySite"
description: "A Jekyll site using Creative Theme"
remote_theme:  "volny/creative-theme-jekyll"

# Plugins used by the site (GitHub Pages-compatible)
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-sitemap

# (Optional) URL settings â€“ set these after your site is published
url: "https://ale4.github.io"
baseurl: "/umbrella"

# (Optional) Exclude files from the site build
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
 
